### ISSUE TITLE
Should consumption constraint in Exercise 2.1 be c_s < 0 rather than c_s <= 0?

### ISSUE THREAD

**Issue by MaxGhenis** [OpenRG/OGprimer#3]
Exercise 2.1 from [Chapter 2](https://github.com/OpenRG/OGprimer/blob/master/Chapters/OGtext_ch02.pdf) asks to define consumption constraint violations as c_s <= 0, but later states it as a nonnegativity constraint. Should it be c_s < 0 instead?

![image](https://user-images.githubusercontent.com/6076111/84794289-ef298c00-afaa-11ea-9232-905ba8c724cc.png)

**Comment by MaxGhenis** [comment]
Similarly, should `K_cnstr` be True for `K < 0` rather than `K <= 0`?
![image](https://user-images.githubusercontent.com/6076111/84801642-47b15700-afb4-11ea-87b9-30d47baa4560.png)

**Comment by MaxGhenis** [comment]
Per the chat today, sounds like consumption has to be positive in order for the CRRA to be defined. Should the constraints be called positivity instead of nonnegativity then?

**Comment by rickecon** [comment]
@MaxGhenis 
1. The question about the aggregate capital stock in Exercise 2.1 is written correctly in the text. The point of the exercise is to highlight values of the variables that violate equilibrium constraints. The aggregate capital stock `K_t` must be strictly positive in equilbrium `K_t > 0` because the production function is not defined for nonpositive capital `K_t <= 0`. It is this last condition that the `feasible()` function in the exercise highlights.

2. Your question about the nonnegativity constraint of consumption `c_{s,t} >= 0` in Section 2.1 is an intricate one. The most general specification of the constraint is the one mentioned in Section 2.1. However, in equilibrium, consumption is strictly positive `c_{s,t} > 0` for two reasons. First, the utility function is not defined for `c <= 0`. Second, the Inada condition of the utility function that the limit of the marginal utility goes to infinity as `c` goes to zero `lim_{c --> 0} u'(c)=infty` ensures that the optimal household decision will be strictly positive consumption `c > 0` (an interior solution). Because these two reasons are equilibrium conditions, it is helpful to first list the constraint as a nonnegativity constraint. I updated the language in Section 2.1 to more accurately reflect this discussion in PR #6.
<img width="1000" alt="Screen Shot 2020-10-09 at 2 05 08 PM" src="https://user-images.githubusercontent.com/4317690/95626911-7312f280-0a38-11eb-8901-c995d0467451.png">
...
<img width="1006" alt="Screen Shot 2020-10-09 at 2 05 31 PM" src="https://user-images.githubusercontent.com/4317690/95626935-802fe180-0a38-11eb-9397-0eccb375171c.png">
